config/routes.rb
Rails.application.routes.draw do
  root 'freelancers#index'

  resources :freelancers do
    member do
      get :confirm_email
      get :expired
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coworking_area.rb
class CoworkingArea < ApplicationRecord

    has_many :freelancers

end

app/models/freelancer.rb
class Freelancer < ApplicationRecord

    before_create :set_confirmation_token

    validates :name,
                presence: true

    validates :email,
                presence: true,
                format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :phone,
                presence: true

    validates :bio,
                presence: true

    enum status: [:confirm, :accept, :expired, :unconfirmed]
    after_initialize :set_default_status


    belongs_to :coworking_area, optional: true

    def validate_email
      self.email_confirmed = true
      self.confirm_token = nil
      self.status = :confirm
      self.save
    end

    private

    def set_default_status
      self.status ||= :unconfirmed
    end

    def set_confirmation_token
      if self.confirm_token.blank?
        self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @freelancers = Freelancer.all
  end

  def new
    @freelancer = Freelancer.new
  end

  def create
    @freelancer = Freelancer.new(freelancer_params)

    if @freelancer.save
      logger.debug ENV["HEROSENDGRID_USERNAME"]
      logger.debug ENV["HEROSENDGRID_PASSWORD"]
      UserMailer.confirmation_email(@freelancer).deliver_now
      redirect_to root_url, notice: 'Votre demande est enregistrée, confirmez votre email.'
    else
      render :new
    end
  end

  def confirm_email
    freelancer = Freelancer.find_by(confirm_token: params[:confirm_token])
    @freelancer = freelancer
    if @freelancer
      @freelancer.validate_email
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  def edit
    freelancer = Freelancer.find_by(id: params[:id])
    @freelancer = freelancer
  end

  def update
    @freelancer = Freelancer.find_by(id: params[:id])

    if @freelancer.update(freelancer_params)
      if Freelancer.accept.size < 4
        redirect_to root_path, notice: 'Vos infos ont été mises à jour.'
      else
        @freelancer.confirm!
        redirect_to root_path, notice: 'Nope!'
      end
    else
      render :edit
    end
  end

  def destroy
    freelancer = Freelancer.find_by(id: params[:id])
    freelancer.destroy
    redirect_to root_path, notice: 'Ce freelancer est retiré de la liste.'
  end

  def expired
    @freelancer = Freelancer.find_by(id: params[:id])
    @freelancer.expired!
    redirect_to root_path, notice: 'Ce freelancer s\'est retiré de la liste d\'attente.'
  end

  private

  def freelancer_params
    params.require(:freelancer).permit(:name, :email, :phone, :bio, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/freelancers_helper.rb
module FreelancersHelper
end

app/views/freelancers/edit.html.erb
<section class="edit-freelancer">
    <header>
        <h1>Editer les infos d'un freelancer</h1>
    </header>

    <div class="row">
        <div class="col-sm-6">
            <%= render "shared/form" %>
        </div>
    </div>
</section>

app/views/freelancers/expired.html.erb
<%= form_for @freelancer, :url => { action: :expired } do |f| %>
    <div class="form-group">
        <%= button_to "Me retirer de la liste d'attente" %>
    </div>
<% end %>

app/views/freelancers/index.html.erb
<section class="all-applies">
    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Email</th>
                <th>Tél</th>
                <th>Biographie</th>
                <th>statut</th>
                <th>Date de création</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @freelancers.each do |freelancer| %>
                <tr>
                    <td><%= freelancer.name %></td>
                    <td><%= freelancer.email %></td>
                    <td><%= freelancer.phone %></td>
                    <td><%= freelancer.bio %></td>

                    <td>
                        <%= form_for (freelancer) do |f| %>
                            <%= f.select(:status, Freelancer.statuses.keys {|status| status}) %>
                            <%= f.submit 'Changer le statut', class: 'button-xs' %>
                        <% end %>
                    </td>

                    <td><%= time_ago_in_words(freelancer.created_at) %> ago</td>
                    <td><%= link_to "modifier", edit_freelancer_path(freelancer) %>
                        <%= link_to "supprimer", freelancer, method: :delete, data: { confirm: "Êtes-vous sûr.e?" } %>
                    </td>
                </tr>
            <% end%>
        </tbody>
    </table>
</section>

app/views/freelancers/new.html.erb
<section class="new-freelancer">
    <header>
        <h1>Apply to our unbelievable waiting list !</h1>
    </header>

    <div class="row">
        <div class="col-sm-6">
            <%= render "shared/form" %>
        </div>
    </div>
</section>

app/views/freelancers/show.html.erb
<h1>Freelancers#show</h1>
<p>Find me in app/views/freelancers/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coworking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body class="container">
    <%= render "shared/navbar" %>
    <main>
      <% if flash[:notice] %>
        <p class="alert alert-info">
          <%= flash[:notice] %>
        </p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <ul class="errors alert alert-danger">
        <% object.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>

app/views/shared/_form.html.erb
<%= form_for @freelancer do |f| %>
    <%= render "shared/errors", object: @freelancer %>

        <div class="form-group">
            <%= f.text_field :name, required: true, class: "form-control", placeholder: "Nom" %>
        </div>

        <div class="form-group">
            <%= f.text_field :email, required: true, class: "form-control", placeholder: "Email" %>
        </div>

        <div class="form-group">
            <%= f.text_field :phone, required: true, class: "form-control", placeholder: "Téléphone" %>
        </div>

        <div class="form-group">
            <%= f.text_area :bio, required: true, class: "form-control", placeholder: "Biographie", rows: 15 %>
        </div>

        <div class="form-group">
            <%= f.button :submit, class: "btn btn-success" %>
        </div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
    <nav>
        <%= link_to "Coworking", root_path, class: "logo" %>

        <div class="navlinks">
            <%= link_to "Inscrire un freelancer", new_freelancer_path %>
        </div>
    </nav>
</header>